### ISSUE TITLE
Error deleting tags

### ISSUE THREAD

**Issue by lugovlac** [eduNEXT/eox-tagging#91]
Hi. Something weird is happening when trying to delete a tag. I'm using this URL format: 

http://localhost:18000/eox-tagging/api/v1/tags/271221f4-487b-467a-a693-45bf1d4092ad

I checked the tag key previously from a tag I created. I make the delete request, but I get a 200 response and this body:

{
    "meta": {
        "target_id": "[CourseEnrollment] edx: course-v1:LaOrganizacion1+gfdhgfhd+v1 (2022-02-07 20:27:30.337870+00:00); active: (True)",
        "target_type": "CourseEnrollment",
        "owner_id": "localhost:18000",
        "owner_type": "Site",
        "created_at": "2022-05-09T14:13:56.957627Z",
        "inactivated_at": null
    },
    "key": "271221f4-487b-467a-a693-45bf1d4092ad",
    "tag_value": "premium",
    "tag_type": "example_tag_3",
    "access": "PUBLIC",
    "activation_date": null,
    "expiration_date": null,
    "status": "ACTIVE"
}

--
this body is very similar to the one you get when you make a GET request, inside the "results" array. Also, the tag does not seem to be deleted (if I make the GET method afterwards, tag's still there). And I don't get the supposed 204 No Content status response, I get 200.

That's it, thanks in advance.

**Comment by dcoa** [comment]
Hello @lugovlac sorry for the late replay, 

I test the delete method like `/api/v1/tags/<tag_key>/` and response 204, and when I check the endpoint to return all tags `/eox-tagging/api/v1/tags/`,  wasn't return the deleted one, please verify you are using DELETE method instead of GET. 

Finally, you can check the Django admin tags `admin/eox_tagging/tag/` and verify the inactive status. 

I'm going to close this issue but if you have still problems please reopen it.
